name: cybersmart
description: CyberSmart - AI Phishing Detector with VirusTotal File Scanner
publish_to: 'none'
version: 2.1.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  shared_preferences: ^2.3.2
  cupertino_icons: ^1.0.8
  tflite_flutter: ^0.10.4
  url_launcher: ^6.2.5
  intl: ^0.19.0
  file_picker: ^8.0.0
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/model.tflite
   ## - assets/model_info.json
